on:
    push:
      branches:
        - main

name: Terraform-Init-Plan-AWS

jobs:
  Terraform-Init-Plan-AWS:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: 'main'
#        fetch-depth: '1'
    - name: 'Print versions'
      run: |
        aws --version
        terraform --version
    - name: 'terraform init, plan'
      timeout-minutes: 20
      env:
        ENV_NAME: 'develop'
      run: |
        ./terraform-init-plan.sh
